#!/bin/sh

if [ "`id -u`" = "0" ]
then
  if [ "${HOME}" = "/root" ]
  then
    echo "You ran this without -E, didn't you..."
    exit
  fi
else
  echo "Root makes the world go round (in an oppressive kind of way)..." \
       "please keep it spinning."
  exit
fi

apt-get -t jessie -y install build-essential autoconf automake libtool \
    flex bison gdb gcc-doc hibernate glibc-doc make-doc libssl-dev \
    libssl-doc libevent-dev manpages-dev asciidoc docbook-xsl docbook-xml \
    xmlto w3m debconf-utils
# Remain with Wheezy, Jessie causes glib conflict
apt-get -y install xscreensaver

apt-get -t jessie -y install mutt offlineimap

apt-get -t jessie -y install libtspi1 libgtkspell-3-0 locales
service tor stop

Persistent/tweak_torrc
echo "SocksPort unix:/run/tor/socks/socks WorldWritable" >> /etc/tor/torrc
mkdir -m 755 /run/tor/socks
chown debian-tor /run/tor/socks
mkdir -m 750 /run/tor/control
chown debian-tor /run/tor/control
cp -ab ${HOME}/Persistent/repos/tor/src/or/tor /usr/bin/tor
chmod 0755 /usr/bin/tor
chown root:root /usr/bin/tor
sudo sed --in-place \
    's/mkdir -m 02750 "\$TORPIDDIR"/mkdir -m 02751 "\$TORPIDDIR"/' \
    /etc/init.d/tor
if [ -e /var/run/tor ]
then
  chmod o+x /var/run/tor
fi
echo "[Tor]
Changed=true
ControlSocket=/var/run/tor/control/control
AuthCookie=/var/run/tor/control"
echo "/{,var/}run/tor/socks/socks w," >> /etc/apparmor.d/local/system_tor
sed --in-place -e 's,tor/control,tor/control/control,g' /etc/apparmor.d/system_tor
sed --in-place -e 's,tor/control,tor/control/control,g' /usr/share/tor/tor-service-defaults-torrc


service apparmor reload
service tor start

${HOME}/Persistent/repos/help_me_do_things/install_torsocks

# ${HOME}/Persistent/configure_iptables

sudo -u amnesia nohup xscreensaver -nosplash &>/dev/null &

echo "amnesia ALL = NOPASSWD: SETENV: /usr/bin/unshare" >> \
    /etc/sudoers.d/zzz_unshare

echo "locales locales/default_environment_locale select en_US.UTF-8" | \
    debconf-set-selections
echo "locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8" | \
    debconf-set-selections
locale-gen

restart-vidalia
